# golangci-lint configuration for NEXUS
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck          # Check for unchecked errors
    - gosimple          # Simplify code
    - govet             # Go vet examines Go source code
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Advanced Go linter
    - unused            # Checks for unused constants, variables, functions and types
    - gofmt             # Check code formatting
    - goimports         # Check import formatting
    - misspell          # Detect commonly misspelled words
    - unconvert         # Remove unnecessary type conversions
    - unparam           # Report unused function parameters
    - gosec             # Security-focused linter
    - goconst           # Find repeated strings that could be constants
    - gocyclo           # Cyclomatic complexity
    - dupl              # Code clone detection
    - gocritic          # Comprehensive linter
    - revive            # Fast, configurable, extensible linter
    - bodyclose         # Check HTTP response bodies are closed
    - noctx             # Check for sending HTTP requests without context
    - sqlclosecheck     # Check SQL rows/statements are closed
    - rowserrcheck      # Check for SQL rows.Err()
    - wastedassign      # Find wasted assignment statements
    - whitespace        # Check for unnecessary whitespace

  disable:
    - exhaustive        # Too strict for switch statements
    - exhaustruct       # Too strict for struct initialization
    - varnamelen        # Variable names can be short in small scopes
    - wsl               # Too opinionated about whitespace
    - nlreturn          # Too strict about return statements
    - lll               # Line length is handled by gofmt
    - funlen            # Function length warnings are too strict
    - cyclop            # Duplicate of gocyclo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/rs/zerolog.Event).Msg
      - (*github.com/rs/zerolog.Event).Msgf

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G204  # Subprocess with variable (needed for agents)
      - G304  # File path from variable (needed for plugin system)
    
  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  dupl:
    threshold: 100

  misspell:
    locale: US
    ignore-words:
      - nexus
      - llama
      - ollama
      - wasm
      - wazero
      - mdns

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - whyNoLint  # We use //nolint comments
      - hugeParam  # Sometimes large structs are passed by value intentionally

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: true  # Not all packages need comments yet
      - name: var-naming
        severity: warning
        arguments:
          - ["ID"]  # Allow ID instead of Id

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    # Exclude specific directories
    - path: (vendor|examples|docs)/
      linters:
        - all
    
    # Ignore long lines in examples
    - path: examples/
      linters:
        - lll
    
    # Allow embed.FS to be unused initially
    - text: "`.*FS` is unused"
      linters:
        - unused
    
    # Temporary: Ignore missing error checks during alpha
    - text: "Error return value of .* is not checked"
      linters:
        - errcheck
      path: internal/
    
    # Allow TODO comments during development
    - text: "Line contains TODO"
      linters:
        - godox

  # Show all issues from a linter
  new: false
  
  # Fix issues automatically where possible
  fix: false

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
