# golangci-lint configuration for NEXUS (Alpha Stage)
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck          # Check for unchecked errors
    - gosimple          # Simplify code
    - govet             # Go vet examines Go source code
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Advanced Go linter
    - unused            # Checks for unused constants, variables, functions and types
    - gofmt             # Check code formatting
    - goimports         # Check import formatting
    - misspell          # Detect commonly misspelled words

  disable:
    - gosec             # Too strict for alpha, re-enable for beta
    - gocritic          # Too strict for alpha
    - revive            # Too strict for alpha
    - unconvert         # Minor optimizations
    - unparam           # Reported but not blocking
    - goconst           # Nice-to-have
    - gocyclo           # Complexity checked in code review
    - dupl              # Code duplication allowed during prototyping
    - bodyclose         # Will be caught in integration tests
    - noctx             # Context usage enforced in security review
    - sqlclosecheck     # Resource cleanup in dedicated review
    - rowserrcheck      # SQL-specific
    - wastedassign      # Optimization pass later
    - whitespace        # gofmt handles this
    - exhaustive        # Too strict for switch statements
    - exhaustruct       # Too strict for struct initialization
    - varnamelen        # Variable names can be short in small scopes
    - wsl               # Too opinionated about whitespace
    - nlreturn          # Too strict about return statements
    - lll               # Line length is handled by gofmt
    - funlen            # Function length warnings are too strict
    - cyclop            # Duplicate of gocyclo

linters-settings:
  errcheck:
    check-type-assertions: false  # Too strict for alpha
    check-blank: false
    exclude-functions:
      - (*github.com/rs/zerolog.Event).Msg
      - (*github.com/rs/zerolog.Event).Msgf
      - (*github.com/rs/zerolog.Logger).Print
      - fmt.Print
      - fmt.Println
      - fmt.Printf
    
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

  misspell:
    locale: US
    ignore-words:
      - nexus
      - llama
      - ollama
      - wasm
      - wazero
      - mdns
      - groq
      - anthropic

  staticcheck:
    checks: ["all", "-SA1019"]  # Exclude deprecation warnings

issues:
  exclude-use-default: true  # Use default excludes
  max-issues-per-linter: 50  # Limit output
  max-same-issues: 10
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - staticcheck
    
    # Exclude specific directories
    - path: (vendor|examples|docs|testdata)/
      linters:
        - all
    
    # Allow embed.FS to be unused initially
    - text: "`.*FS` is unused"
      linters:
        - unused
    
    # Temporary: Ignore missing error checks during alpha
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
    
    # Allow TODO comments during development
    - text: "(TODO|FIXME|XXX)"
      linters:
        - godox
    
    # Ignore context.Background() in examples and tests
    - text: "Non-inherited new context"
      path: (examples|_test)\.go
    
    # Ignore shadow variables in tests
    - text: "shadow"
      path: _test\.go
    
    # Allow time.Sleep in mesh simulation
    - text: "time\.Sleep"
      path: internal/mesh/
    
    # Allow exec.Command in forge/compiler
    - text: "subprocess launched with variable"
      path: internal/forge/

  # Show only new issues
  new: false
  
  # Don't auto-fix
  fix: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
