# golangci-lint configuration for NEXUS (Alpha Stage - Minimal)
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck          # Check for unchecked errors (critical)
    - gosimple          # Simplify code
    - govet             # Go vet examines Go source code
    - gofmt             # Check code formatting
    - goimports         # Check import formatting

  disable:
    - staticcheck       # Too many false positives for alpha
    - ineffassign       # Optimization pass later
    - unused            # Too strict during prototyping
    - misspell          # Nice-to-have
    - gosec             # Security review in beta
    - gocritic          # Too opinionated
    - revive            # Style enforcement later
    - unconvert         # Minor optimizations
    - unparam           # Reported but not blocking
    - goconst           # Nice-to-have
    - gocyclo           # Complexity checked in code review
    - dupl              # Code duplication allowed during prototyping
    - bodyclose         # Will be caught in integration tests
    - noctx             # Context usage enforced in security review
    - sqlclosecheck     # Resource cleanup in dedicated review
    - rowserrcheck      # SQL-specific
    - wastedassign      # Optimization pass later
    - whitespace        # gofmt handles this

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (*github.com/rs/zerolog.Event).Msg
      - (*github.com/rs/zerolog.Event).Msgf
      - (*github.com/rs/zerolog.Logger).Print
      - fmt.Print
      - fmt.Println
      - fmt.Printf
    
  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    # Exclude linters from test files
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
    
    # Exclude specific directories
    - path: (vendor|examples|docs|testdata)/
      linters:
        - all
    
    # Allow TODO comments
    - text: "(TODO|FIXME|XXX)"
      linters:
        - godox
    
    # Allow time.Sleep in mesh simulation
    - text: "time\.Sleep"
      path: internal/mesh/
    
    # Allow exec.Command in forge/compiler
    - text: "subprocess launched with variable"
      path: internal/forge/

  new: false
  fix: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
