project_name: nexus
builds:
  - main: ./cmd/nexus
    binary: nexus
    env: [CGO_ENABLED=1]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
release:
  github:
    owner: Omkar0612
    name: nexus-ai
changelog:
  sort: asc
