package predictive

import (
	"time"
)

// EventType categorizes the incoming trigger that warrants pre-computation.
type EventType string

const (
	EventUpcomingMeeting EventType = "MEETING"
	EventBrokenBuild     EventType = "BROKEN_BUILD"
	EventNewEmail        EventType = "HIGH_PRIORITY_EMAIL"
)

// Event represents a trigger from an external system (Calendar, GitHub, etc.)
type Event struct {
	ID        string
	Type      EventType
	Timestamp time.Time
	Payload   map[string]interface{}
}

// PrecomputedResult is the cached output generated by NEXUS in the background.
type PrecomputedResult struct {
	EventID   string
	Summary   string
	Action    string // The suggested next step (e.g. "Send Email", "Apply Patch")
	Data      []byte // The actual report or patch file
	CreatedAt time.Time
	Viewed    bool
}

// EventSource defines an interface for polling systems (like Google Calendar or GitHub Actions).
type EventSource interface {
	Poll() ([]Event, error)
	Name() string
}

// Cache defines where we store the pre-computed results so the UI can instantly load them.
type Cache interface {
	Store(result *PrecomputedResult) error
	GetUnviewed() ([]*PrecomputedResult, error)
	MarkViewed(eventID string) error
}
